# Generated by Django 3.1.7 on 2022-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_created_date_remove_movie_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moviedescription',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieitem',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieComment',
        ),
        migrations.DeleteModel(
            name='MovieDescription',
        ),
        migrations.DeleteModel(
            name='MovieItem',
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
